ERROR:root:test exeption message :[1, 3, 6]
Traceback (most recent call last):
  File "/Users/endotakumi/OneDrive - 遠藤 拓巳/00_個人フォルダ/10_学校/1年次/2020_1_前期_プログラミング実習1/スキルアップ教科書/Chap8/code4-05.py", line 6, in <module>
    raise Exception
Exception
